name: Deploy Hugo

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Важно для тем-подмодулей

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.136.5'  # Укажите вашу версию Hugo
          extended: true  # Если используете extended-версию

      - name: Build
        run: hugo --minify --baseURL "https://xerogi2k.github.io/ovos_lab3/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
